//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 612
using System;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.Generic;
using System.Text;
using Gravitybox.gFileSystem.EFDAL;
using Gravitybox.gFileSystem.EFDAL.EventArguments;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data.Linq;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;

namespace Gravitybox.gFileSystem.EFDAL.Entity
{
	/// <summary>
	/// The 'FileStash' entity
	/// </summary>
	[DataContract]
	[Serializable]
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	[FieldNameConstants(typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants))]
	[System.ComponentModel.DataAnnotations.MetadataType(typeof(Gravitybox.gFileSystem.EFDAL.Entity.Metadata.FileStashMetadata))]
	[EntityMetadata("FileStash", false, true, true, true, "", true, false, false, "dbo")]
	public partial class FileStash : BaseEntity, Gravitybox.gFileSystem.EFDAL.IBusinessObject, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging, System.ICloneable, Gravitybox.gFileSystem.EFDAL.IAuditable, Gravitybox.gFileSystem.EFDAL.IAuditableSet, Gravitybox.gFileSystem.EFDAL.ICreatable
	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'FileStash' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'ContainerId' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ContainerId' property")]
			ContainerId,
			/// <summary>
			/// Field mapping for the 'CrcPlain' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CrcPlain' property")]
			CrcPlain,
			/// <summary>
			/// Field mapping for the 'FileStashID' property
			/// </summary>
			[System.ComponentModel.DataAnnotations.Key]
			[System.ComponentModel.ReadOnly(true)]
			[System.ComponentModel.Description("Field mapping for the 'FileStashID' property")]
			FileStashID,
			/// <summary>
			/// Field mapping for the 'IsCompressed' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'IsCompressed' property")]
			IsCompressed,
			/// <summary>
			/// Field mapping for the 'Path' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Path' property")]
			Path,
			/// <summary>
			/// Field mapping for the 'Size' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Size' property")]
			Size,
			/// <summary>
			/// Field mapping for the 'StorageSize' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'StorageSize' property")]
			StorageSize,
			/// <summary>
			/// Field mapping for the 'TenantID' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'TenantID' property")]
			TenantID,
			/// <summary>
			/// Field mapping for the 'UniqueKey' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'UniqueKey' property")]
			UniqueKey,
			/// <summary>
			/// Field mapping for the 'CreatedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedBy' property")]
			CreatedBy,
			/// <summary>
			/// Field mapping for the 'CreatedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedDate' property")]
			CreatedDate,
			/// <summary>
			/// Field mapping for the 'ModifiedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedBy' property")]
			ModifiedBy,
			/// <summary>
			/// Field mapping for the 'ModifiedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedDate' property")]
			ModifiedDate,
		}
		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the Gravitybox.gFileSystem.EFDAL.Entity.FileStash class
		/// </summary>
		public FileStash()
		{
			this._isCompressed = false;
			this._storageSize = 0L;
			this._uniqueKey = Guid.NewGuid();

		}

		#endregion

		#region Properties

		/// <summary>
		/// The property that maps back to the database 'FileStash.ContainerId' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[ContainerId], Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("ContainerId")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual long? ContainerId
		{
			get { return _containerId; }
			set
			{
				if (value == _containerId) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long?>(value, "ContainerId");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_containerId = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ContainerId"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.CrcPlain' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[CrcPlain], Field Length: 32, Not Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("CrcPlain")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string CrcPlain
		{
			get { return _crcPlain; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CrcPlain))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "FileStash.CrcPlain", GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CrcPlain)));
				if (value == _crcPlain) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "CrcPlain");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_crcPlain = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CrcPlain"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.FileStashID' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[FileStashID], Not Nullable, Primary Key, AutoNumber, Unique, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("FileStashID")]
		[System.ComponentModel.DataAnnotations.Schema.Index(IsUnique = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual long FileStashID
		{
			get { return _fileStashID; }
			protected internal set
			{
				if (value == _fileStashID) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>(value, "FileStashID");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_fileStashID = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("FileStashID"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.IsCompressed' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[IsCompressed], Not Nullable, Default Value: 0</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("IsCompressed")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual bool IsCompressed
		{
			get { return _isCompressed; }
			set
			{
				if (value == _isCompressed) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<bool>(value, "IsCompressed");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_isCompressed = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("IsCompressed"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.Path' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[Path], Field Length: 450, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Path")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string Path
		{
			get { return _path; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Path))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "FileStash.Path", GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Path)));
				if (value == _path) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "Path");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_path = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Path"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.Size' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[Size], Not Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Size")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual long Size
		{
			get { return _size; }
			set
			{
				if (value == _size) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>(value, "Size");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_size = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Size"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.StorageSize' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[StorageSize], Not Nullable, Default Value: 0</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("StorageSize")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual long StorageSize
		{
			get { return _storageSize; }
			set
			{
				if (value == _storageSize) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>(value, "StorageSize");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_storageSize = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("StorageSize"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.TenantID' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[TenantID], Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("TenantID")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual long TenantID
		{
			get { return _tenantID; }
			set
			{
				if (value == _tenantID) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>(value, "TenantID");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_tenantID = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("TenantID"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'FileStash.UniqueKey' field.
		/// </summary>
		/// <remarks>Field: [FileStash].[UniqueKey], Not Nullable, Indexed, Default Value: newid</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("UniqueKey")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual System.Guid UniqueKey
		{
			get { return _uniqueKey; }
			set
			{
				if (value == _uniqueKey) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Guid>(value, "UniqueKey");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_uniqueKey = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("UniqueKey"));
			}
		}

		/// <summary>
		/// The audit field for the 'Created By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string CreatedBy
		{
			get { return _createdby; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "CreatedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createdby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedBy"));
			}
		}

		/// <summary />
		protected string _createdby;

		/// <summary>
		/// The audit field for the 'Created Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual DateTime? CreatedDate
		{
			get { return _createddate; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>(value, "CreatedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedDate"));
			}
		}

		/// <summary />
		protected DateTime? _createddate;

		/// <summary>
		/// The audit field for the 'Modified By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string ModifiedBy
		{
			get { return _modifiedby; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "ModifiedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifiedby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedBy"));
			}
		}

		/// <summary />
		protected string _modifiedby;

		/// <summary>
		/// The audit field for the 'Modified Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual DateTime? ModifiedDate
		{
			get { return _modifieddate; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>(value, "ModifiedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifieddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedDate"));
			}
		}

		/// <summary />
		protected DateTime? _modifieddate;

		/// <summary>
		/// The audit field for the 'Timestamp' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual byte[] Timestamp
		{
			get { return _timestamp; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<byte[]>(value, "Timestamp");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_timestamp = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Timestamp"));
			}
		}

		/// <summary />
		protected byte[] _timestamp;

		#endregion

		#region Property Holders

		/// <summary />
		protected long? _containerId;
		/// <summary>
		/// Occurs when the 'ContainerId' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long?>> ContainerIdChanging;

		/// <summary>
		/// Raises the OnContainerIdChanging event.
		/// </summary>
		protected virtual void OnContainerIdChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long?> e)
		{
			if (this.ContainerIdChanging != null)
				this.ContainerIdChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ContainerId' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<long?>> ContainerIdChanged;

		/// <summary>
		/// Raises the OnContainerIdChanged event.
		/// </summary>
		protected virtual void OnContainerIdChanged(ChangedEventArgs<long?> e)
		{
			if (this.ContainerIdChanged != null)
				this.ContainerIdChanged(this, e);
		}

		/// <summary />
		protected string _crcPlain;
		/// <summary>
		/// Occurs when the 'CrcPlain' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> CrcPlainChanging;

		/// <summary>
		/// Raises the OnCrcPlainChanging event.
		/// </summary>
		protected virtual void OnCrcPlainChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CrcPlainChanging != null)
				this.CrcPlainChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CrcPlain' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> CrcPlainChanged;

		/// <summary>
		/// Raises the OnCrcPlainChanged event.
		/// </summary>
		protected virtual void OnCrcPlainChanged(ChangedEventArgs<string> e)
		{
			if (this.CrcPlainChanged != null)
				this.CrcPlainChanged(this, e);
		}

		/// <summary />
		protected long _fileStashID;
		/// <summary>
		/// Occurs when the 'FileStashID' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>> FileStashIDChanging;

		/// <summary>
		/// Raises the OnFileStashIDChanging event.
		/// </summary>
		protected virtual void OnFileStashIDChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long> e)
		{
			if (this.FileStashIDChanging != null)
				this.FileStashIDChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'FileStashID' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<long>> FileStashIDChanged;

		/// <summary>
		/// Raises the OnFileStashIDChanged event.
		/// </summary>
		protected virtual void OnFileStashIDChanged(ChangedEventArgs<long> e)
		{
			if (this.FileStashIDChanged != null)
				this.FileStashIDChanged(this, e);
		}

		/// <summary />
		protected bool _isCompressed;
		/// <summary>
		/// Occurs when the 'IsCompressed' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<bool>> IsCompressedChanging;

		/// <summary>
		/// Raises the OnIsCompressedChanging event.
		/// </summary>
		protected virtual void OnIsCompressedChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<bool> e)
		{
			if (this.IsCompressedChanging != null)
				this.IsCompressedChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'IsCompressed' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<bool>> IsCompressedChanged;

		/// <summary>
		/// Raises the OnIsCompressedChanged event.
		/// </summary>
		protected virtual void OnIsCompressedChanged(ChangedEventArgs<bool> e)
		{
			if (this.IsCompressedChanged != null)
				this.IsCompressedChanged(this, e);
		}

		/// <summary />
		protected string _path;
		/// <summary>
		/// Occurs when the 'Path' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> PathChanging;

		/// <summary>
		/// Raises the OnPathChanging event.
		/// </summary>
		protected virtual void OnPathChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.PathChanging != null)
				this.PathChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Path' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> PathChanged;

		/// <summary>
		/// Raises the OnPathChanged event.
		/// </summary>
		protected virtual void OnPathChanged(ChangedEventArgs<string> e)
		{
			if (this.PathChanged != null)
				this.PathChanged(this, e);
		}

		/// <summary />
		protected long _size;
		/// <summary>
		/// Occurs when the 'Size' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>> SizeChanging;

		/// <summary>
		/// Raises the OnSizeChanging event.
		/// </summary>
		protected virtual void OnSizeChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long> e)
		{
			if (this.SizeChanging != null)
				this.SizeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Size' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<long>> SizeChanged;

		/// <summary>
		/// Raises the OnSizeChanged event.
		/// </summary>
		protected virtual void OnSizeChanged(ChangedEventArgs<long> e)
		{
			if (this.SizeChanged != null)
				this.SizeChanged(this, e);
		}

		/// <summary />
		protected long _storageSize;
		/// <summary>
		/// Occurs when the 'StorageSize' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>> StorageSizeChanging;

		/// <summary>
		/// Raises the OnStorageSizeChanging event.
		/// </summary>
		protected virtual void OnStorageSizeChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long> e)
		{
			if (this.StorageSizeChanging != null)
				this.StorageSizeChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'StorageSize' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<long>> StorageSizeChanged;

		/// <summary>
		/// Raises the OnStorageSizeChanged event.
		/// </summary>
		protected virtual void OnStorageSizeChanged(ChangedEventArgs<long> e)
		{
			if (this.StorageSizeChanged != null)
				this.StorageSizeChanged(this, e);
		}

		/// <summary />
		protected long _tenantID;
		/// <summary>
		/// Occurs when the 'TenantID' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>> TenantIDChanging;

		/// <summary>
		/// Raises the OnTenantIDChanging event.
		/// </summary>
		protected virtual void OnTenantIDChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long> e)
		{
			if (this.TenantIDChanging != null)
				this.TenantIDChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'TenantID' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<long>> TenantIDChanged;

		/// <summary>
		/// Raises the OnTenantIDChanged event.
		/// </summary>
		protected virtual void OnTenantIDChanged(ChangedEventArgs<long> e)
		{
			if (this.TenantIDChanged != null)
				this.TenantIDChanged(this, e);
		}

		/// <summary />
		protected System.Guid _uniqueKey;
		/// <summary>
		/// Occurs when the 'UniqueKey' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Guid>> UniqueKeyChanging;

		/// <summary>
		/// Raises the OnUniqueKeyChanging event.
		/// </summary>
		protected virtual void OnUniqueKeyChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Guid> e)
		{
			if (this.UniqueKeyChanging != null)
				this.UniqueKeyChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'UniqueKey' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<System.Guid>> UniqueKeyChanged;

		/// <summary>
		/// Raises the OnUniqueKeyChanged event.
		/// </summary>
		protected virtual void OnUniqueKeyChanged(ChangedEventArgs<System.Guid> e)
		{
			if (this.UniqueKeyChanged != null)
				this.UniqueKeyChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> CreatedByChanging;

		/// <summary>
		/// Raises the OnCreatedByChanging event.
		/// </summary>
		protected virtual void OnCreatedByChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CreatedByChanging != null)
				this.CreatedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> CreatedByChanged;

		/// <summary>
		/// Raises the OnCreatedByChanged event.
		/// </summary>
		protected virtual void OnCreatedByChanged(ChangedEventArgs<string> e)
		{
			if (this.CreatedByChanged != null)
				this.CreatedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>> CreatedDateChanging;

		/// <summary>
		/// Raises the OnCreatedDateChanging event.
		/// </summary>
		protected virtual void OnCreatedDateChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?> e)
		{
			if (this.CreatedDateChanging != null)
				this.CreatedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<DateTime?>> CreatedDateChanged;

		/// <summary>
		/// Raises the OnCreatedDateChanged event.
		/// </summary>
		protected virtual void OnCreatedDateChanged(ChangedEventArgs<DateTime?> e)
		{
			if (this.CreatedDateChanged != null)
				this.CreatedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> ModifiedByChanging;

		/// <summary>
		/// Raises the OnModifiedByChanging event.
		/// </summary>
		protected virtual void OnModifiedByChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.ModifiedByChanging != null)
				this.ModifiedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> ModifiedByChanged;

		/// <summary>
		/// Raises the OnModifiedByChanged event.
		/// </summary>
		protected virtual void OnModifiedByChanged(ChangedEventArgs<string> e)
		{
			if (this.ModifiedByChanged != null)
				this.ModifiedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>> ModifiedDateChanging;

		/// <summary>
		/// Raises the OnModifiedDateChanging event.
		/// </summary>
		protected virtual void OnModifiedDateChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?> e)
		{
			if (this.ModifiedDateChanging != null)
				this.ModifiedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<DateTime?>> ModifiedDateChanged;

		/// <summary>
		/// Raises the OnModifiedDateChanged event.
		/// </summary>
		protected virtual void OnModifiedDateChanged(ChangedEventArgs<DateTime?> e)
		{
			if (this.ModifiedDateChanged != null)
				this.ModifiedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'Timestamp' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<byte[]>> TimestampChanging;

		/// <summary>
		/// Raises the OnTimestampChanging event.
		/// </summary>
		protected virtual void OnTimestampChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<byte[]> e)
		{
			if (this.TimestampChanging != null)
				this.TimestampChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Timestamp' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<byte[]>> TimestampChanged;

		/// <summary>
		/// Raises the OnTimestampChanged event.
		/// </summary>
		protected virtual void OnTimestampChanged(ChangedEventArgs<byte[]> e)
		{
			if (this.TimestampChanged != null)
				this.TimestampChanged(this, e);
		}


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field)
		{
			switch (field)
			{
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.ContainerId:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CrcPlain:
					return 32;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.FileStashID:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.IsCompressed:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Path:
					return 450;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Size:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.StorageSize:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.TenantID:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.UniqueKey:
					return 0;
			}
			return 0;
		}

		int Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetMaxLength(Enum field)
		{
			return GetMaxLength((Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants)field);
		}

		#endregion

		#region GetFieldNameConstants

		System.Type Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetFieldNameConstants()
		{
			return typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants);
		}

		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants'.");

			switch ((Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants)field)
			{
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.ContainerId: return typeof(long?);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CrcPlain: return typeof(string);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.FileStashID: return typeof(long);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.IsCompressed: return typeof(bool);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Path: return typeof(string);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Size: return typeof(long);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.StorageSize: return typeof(long);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.TenantID: return typeof(long);
				case Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.UniqueKey: return typeof(System.Guid);
			}
			return null;
		}

		System.Type Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetFieldType(Enum field)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants'.");

			return GetFieldType((Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants)field);
		}

		#endregion

		#region Get/Set Value

		object Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field)
		{
			return ((Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject)this).GetValue(field, null);
		}

		object Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field, object defaultValue)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants'.");
			return this.GetValue((Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants)field, defaultValue);
		}

		void Gravitybox.gFileSystem.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants'.");
			this.SetValue((Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants)field, newValue);
		}

		void Gravitybox.gFileSystem.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue, bool fixLength)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants'.");
			this.SetValue((Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants)field, newValue, fixLength);
		}

		#endregion

		#region PrimaryKey

		/// <summary>
		/// Generic primary key for this object
		/// </summary>
		Gravitybox.gFileSystem.EFDAL.IPrimaryKey Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.PrimaryKey
		{
			get { return new PrimaryKey(Util.HashPK("FileStash", this.FileStashID)); }
		}

		#endregion

		#region Clone

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public virtual object Clone()
		{
			return Gravitybox.gFileSystem.EFDAL.Entity.FileStash.Clone(this);
		}

		/// <summary>
		/// Creates a shallow copy of this object with defined, default values and new PK
		/// </summary>
		public virtual object CloneAsNew()
		{
			var item = Gravitybox.gFileSystem.EFDAL.Entity.FileStash.Clone(this);
			item._fileStashID = 0;
			item._isCompressed = false;
			item._storageSize = 0L;
			item._uniqueKey = Guid.NewGuid();
			return item;
		}

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public static FileStash Clone(Gravitybox.gFileSystem.EFDAL.Entity.FileStash item)
		{
			var newItem = new FileStash();
			newItem.ContainerId = item.ContainerId;
			newItem.CrcPlain = item.CrcPlain;
			newItem.FileStashID = item.FileStashID;
			newItem.IsCompressed = item.IsCompressed;
			newItem.Path = item.Path;
			newItem.Size = item.Size;
			newItem.StorageSize = item.StorageSize;
			newItem.TenantID = item.TenantID;
			newItem.UniqueKey = item.UniqueKey;
			newItem.CreatedDate = item.CreatedDate;
			newItem.CreatedBy = item.CreatedBy;
			newItem.ModifiedDate = item.ModifiedDate;
			newItem.ModifiedBy = item.ModifiedBy;
			return newItem;
		}

		#endregion

		#region GetValue

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field)
		{
			return GetValue(field, null);
		}

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field, object defaultValue)
		{
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.ContainerId)
				return ((this.ContainerId == null) ? defaultValue : this.ContainerId);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CrcPlain)
				return this.CrcPlain;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.FileStashID)
				return this.FileStashID;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.IsCompressed)
				return this.IsCompressed;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Path)
				return this.Path;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Size)
				return this.Size;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.StorageSize)
				return this.StorageSize;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.TenantID)
				return this.TenantID;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.UniqueKey)
				return this.UniqueKey;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CreatedBy)
				return ((this.CreatedBy == null) ? defaultValue : this.CreatedBy);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CreatedDate)
				return ((this.CreatedDate == null) ? defaultValue : this.CreatedDate);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.ModifiedBy)
				return ((this.ModifiedBy == null) ? defaultValue : this.ModifiedBy);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.ModifiedDate)
				return ((this.ModifiedDate == null) ? defaultValue : this.ModifiedDate);
			throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region SetValue

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		public virtual void SetValue(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field, object newValue)
		{
			SetValue(field, newValue, false);
		}

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		/// <param name="fixLength">Determines if the length should be truncated if too long. When false, an error will be raised if data is too large to be assigned to the field.</param>
		public virtual void SetValue(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field, object newValue, bool fixLength)
		{
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.ContainerId)
			{
				this.ContainerId = GlobalValues.SetValueHelperLongNullableInternal(newValue);
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.CrcPlain)
			{
				this.CrcPlain = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.FileStashID)
			{
				throw new Exception("Field '" + field.ToString() + "' is a primary key and cannot be set!");
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.IsCompressed)
			{
				this.IsCompressed = GlobalValues.SetValueHelperBoolNotNullableInternal(newValue, "Field 'IsCompressed' does not allow null values!");
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Path)
			{
				this.Path = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.Size)
			{
				this.Size = GlobalValues.SetValueHelperLongNotNullableInternal(newValue, "Field 'Size' does not allow null values!");
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.StorageSize)
			{
				this.StorageSize = GlobalValues.SetValueHelperLongNotNullableInternal(newValue, "Field 'StorageSize' does not allow null values!");
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.TenantID)
			{
				this.TenantID = GlobalValues.SetValueHelperLongNotNullableInternal(newValue, "Field 'TenantID' does not allow null values!");
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants.UniqueKey)
			{
				if (newValue == null)
				{
					throw new Exception("Field 'UniqueKey' does not allow null values!");
				}
				else
				{
					this.UniqueKey = (System.Guid)newValue;
				}
			}
			else
				throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region Navigation Properties

		/// <summary>
		/// The navigation definition for walking Container->FileStash
		/// </summary>
		[DataMember]
		[XmlIgnore]
		public virtual Container Container { get; set; }

		/// <summary>
		/// The navigation definition for walking Tenant->FileStash
		/// </summary>
		[DataMember]
		[XmlIgnore]
		public virtual Tenant Tenant { get; set; }

		#endregion

		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "containerid": return "containerid";
				case "crcplain": return "crcplain";
				case "filestashid": return "filestashid";
				case "iscompressed": return "iscompressed";
				case "path": return "path";
				case "size": return "size";
				case "storagesize": return "storagesize";
				case "tenantid": return "tenantid";
				case "uniquekey": return "uniquekey";
				case "createddate": return "createddate";
				case "createdby": return "createdby";
				case "modifieddate": return "modifieddate";
				case "modifiedby": return "modifiedby";
				case "timestamp": return "timestamp";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "containerid": return "FileStash";
				case "crcplain": return "FileStash";
				case "filestashid": return "FileStash";
				case "iscompressed": return "FileStash";
				case "path": return "FileStash";
				case "size": return "FileStash";
				case "storagesize": return "FileStash";
				case "tenantid": return "FileStash";
				case "uniquekey": return "FileStash";
				case "createdby": return "FileStash";
				case "createddate": return "FileStash";
				case "modifiedby": return "FileStash";
				case "modifieddate": return "FileStash";
				case "timestamp": return "FileStash";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "containerid": return "FileStash";
				case "crcplain": return "FileStash";
				case "filestashid": return "FileStash";
				case "iscompressed": return "FileStash";
				case "path": return "FileStash";
				case "size": return "FileStash";
				case "storagesize": return "FileStash";
				case "tenantid": return "FileStash";
				case "uniquekey": return "FileStash";
				case "createdby": return "FileStash";
				case "createddate": return "FileStash";
				case "modifiedby": return "FileStash";
				case "modifieddate": return "FileStash";
				case "timestamp": return "FileStash";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[containerid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[containerid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[crcplain\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[crcplain]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[filestashid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[filestashid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[iscompressed\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[iscompressed]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[path\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[path]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[size\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[size]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[storagesize\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[storagesize]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[tenantid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[tenantid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[uniquekey\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[uniquekey]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createdby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[createdby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[createddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifiedby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[modifiedby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifieddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[modifieddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[timestamp\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "FileStash") + "].[timestamp]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion

		#region DeleteData

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: Gravitybox.gFileSystem.EFDAL.gFileSystemEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, QueryOptimizer optimizer)
		{
			return DeleteData(where: where, optimizer: optimizer, startup: new ContextStartup(null), connectionString: Gravitybox.gFileSystem.EFDAL.gFileSystemEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, string connectionString)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: connectionString);
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <param name="startup">The startup options</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, QueryOptimizer optimizer, ContextStartup startup, string connectionString)
		{
			if (optimizer == null)
				optimizer = new QueryOptimizer();
				if (startup == null) startup = new ContextStartup(null);

			using (var connection = Gravitybox.gFileSystem.EFDAL.DBHelper.GetConnection(Gravitybox.gFileSystem.EFDAL.Util.StripEFCS2Normal(connectionString)))
			{
				using (var dc = new DataContext(connection))
				{
					var template = dc.GetTable<Gravitybox.gFileSystem.EFDAL.FileStashQuery>();
					using (var cmd = BusinessEntityQuery.GetCommand<Gravitybox.gFileSystem.EFDAL.FileStashQuery>(dc, template, where))
					{
						if (!startup.DefaultTimeout && startup.CommandTimeout > 0) cmd.CommandTimeout = startup.CommandTimeout;
						else
						{
							var cb = new System.Data.SqlClient.SqlConnectionStringBuilder(connectionString);
							cmd.CommandTimeout = cb.ConnectTimeout;
						}

						var parser = LinqSQLParser.Create(cmd.CommandText, LinqSQLParser.ObjectTypeConstants.Table);
						var sql = "CREATE TABLE #t ([FileStashID] [BigInt])";
						sql += "set rowcount " + optimizer.ChunkSize + ";";
						sql += "INSERT INTO #t ([FileStashID])";
						sql += "SELECT [t0].[FileStashID] #t\r\n";
						sql += parser.GetFromClause(optimizer) + "\r\n";
						sql += parser.GetWhereClause();
						sql += "\r\n";

						var noLock = string.Empty;
						noLock = (optimizer.NoLocking ? "WITH (READUNCOMMITTED) " : string.Empty);
						sql += "DELETE [FileStash] FROM [dbo].[FileStash] " + noLock + "INNER JOIN #t ON [dbo].[FileStash].[FileStashID] = #t.[FileStashID]\r\n";
						sql += ";select @@rowcount";
						sql = "set ansi_nulls off;" + sql + ";drop table #t;";
						cmd.CommandText = sql;
						dc.Connection.Open();
						var startTime = DateTime.Now;
						var affected = 0;
						var count = 0;
						do
						{
							count = (int)cmd.ExecuteScalar();
							affected += count;
						} while (count > 0 && optimizer.ChunkSize > 0);
						var endTime = DateTime.Now;
						optimizer.TotalMilliseconds = (long)endTime.Subtract(startTime).TotalMilliseconds;
						dc.Connection.Close();
						return affected;
					}
				}
			}
		}

		#endregion

		#region UpdateData

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, TSource newValue)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.FileStash, Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "FileStash", getField: GetDatabaseFieldName, hasModifyAudit: true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, TSource newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.FileStash, Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "FileStash", getField: GetDatabaseFieldName, hasModifyAudit: true, startup: null, connection: connection, transaction: transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="startup">A configuration object</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, TSource newValue, ContextStartup startup, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.FileStash, Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "FileStash", getField: GetDatabaseFieldName, hasModifyAudit: true, startup: startup, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, TSource newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.FileStash, Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "FileStash", getField: GetDatabaseFieldName, hasModifyAudit: true, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, Gravitybox.gFileSystem.EFDAL.Entity.FileStash newValue)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.FileStash, Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "FileStash", getField: GetDatabaseFieldName, hasModifyAudit: true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.FileStashQuery, bool>> where, Gravitybox.gFileSystem.EFDAL.Entity.FileStash newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.FileStash, Gravitybox.gFileSystem.EFDAL.FileStashQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "FileStash", getField: GetDatabaseFieldName, hasModifyAudit: true, connectionString: connectionString);
		}

		#endregion

		#region GetDatabaseFieldName

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(Gravitybox.gFileSystem.EFDAL.Entity.FileStash.FieldNameConstants field)
		{
			return GetDatabaseFieldName(field.ToString());
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "ContainerId": return "ContainerId";
				case "CrcPlain": return "CrcPlain";
				case "FileStashID": return "FileStashID";
				case "IsCompressed": return "IsCompressed";
				case "Path": return "Path";
				case "Size": return "Size";
				case "StorageSize": return "StorageSize";
				case "TenantID": return "TenantID";
				case "UniqueKey": return "UniqueKey";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

		#region Auditing
		string Gravitybox.gFileSystem.EFDAL.IAuditableSet.CreatedBy
		{
			get { return this.CreatedBy; }
			set { this.CreatedBy = value; }
		}

		string Gravitybox.gFileSystem.EFDAL.IAuditableSet.ModifiedBy
		{
			get { return this.ModifiedBy; }
			set { this.ModifiedBy = value; }
		}
		string Gravitybox.gFileSystem.EFDAL.IAuditable.CreatedBy
		{
			get { return this.CreatedBy; }
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditable.CreatedDate
		{
			get { return this.CreatedDate; }
		}

		bool Gravitybox.gFileSystem.EFDAL.IAuditable.IsCreateAuditImplemented
		{
			get { return true; }
		}

		bool Gravitybox.gFileSystem.EFDAL.IAuditable.IsModifyAuditImplemented
		{
			get { return true; }
		}

		bool Gravitybox.gFileSystem.EFDAL.IAuditable.IsTimestampAuditImplemented
		{
			get { return true; }
		}

		string Gravitybox.gFileSystem.EFDAL.IAuditable.ModifiedBy
		{
			get { return this.ModifiedBy; }
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditable.ModifiedDate
		{
			get { return this.ModifiedDate; }
		}

		byte[] Gravitybox.gFileSystem.EFDAL.IAuditable.TimeStamp
		{
			get { return this.Timestamp; }
		}

		void IAuditableSet.ResetModifiedBy(string modifier)
		{
			if (this.ModifiedBy != modifier)
				this.ModifiedBy = modifier;
		}

		void IAuditableSet.ResetCreatedBy(string modifier)
		{
			if (this.CreatedBy != modifier)
				this.CreatedBy = modifier;
			((IAuditableSet)this).ResetModifiedBy(modifier);
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditableSet.CreatedDate
		{
			get { return this.CreatedDate; }
			set { this.CreatedDate = value; }
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditableSet.ModifiedDate
		{
			get { return this.ModifiedDate; }
			set { this.ModifiedDate = value; }
		}

		#endregion

		#region Equals
		/// <summary>
		/// Compares two objects of 'FileStash' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		public override bool Equals(object obj)
		{
			var other = obj as Gravitybox.gFileSystem.EFDAL.Entity.FileStash;
			if (other == null) return false;
			return (
				other.ContainerId == this.ContainerId &&
				other.CrcPlain == this.CrcPlain &&
				other.FileStashID == this.FileStashID &&
				other.IsCompressed == this.IsCompressed &&
				other.Path == this.Path &&
				other.Size == this.Size &&
				other.StorageSize == this.StorageSize &&
				other.TenantID == this.TenantID &&
				other.UniqueKey == this.UniqueKey
				);
		}

		/// <summary>
		/// Serves as a hash function for this type.
		/// </summary>
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		#endregion

	}
}

#region Metadata Class

namespace Gravitybox.gFileSystem.EFDAL.Entity.Metadata
{
	/// <summary>
	/// Metadata class for the 'FileStash' entity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	public partial class FileStashMetadata : Gravitybox.gFileSystem.EFDAL.IMetadata
	{
		#region Properties

		/// <summary>
		/// Metadata information for the 'ContainerId' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "ContainerId", AutoGenerateField = true)]
		public object ContainerId;

		/// <summary>
		/// Metadata information for the 'CrcPlain' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'CrcPlain' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(32, ErrorMessage = "The property 'CrcPlain' has a maximum length of 32")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "CrcPlain", AutoGenerateField = true)]
		public object CrcPlain;

		/// <summary>
		/// Metadata information for the 'FileStashID' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'FileStashID' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.ComponentModel.ReadOnly(true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "FileStashID", AutoGenerateField = true)]
		public object FileStashID;

		/// <summary>
		/// Metadata information for the 'IsCompressed' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'IsCompressed' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "IsCompressed", AutoGenerateField = true)]
		public object IsCompressed;

		/// <summary>
		/// Metadata information for the 'Path' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'Path' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(450, ErrorMessage = "The property 'Path' has a maximum length of 450")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Path", AutoGenerateField = true)]
		public object Path;

		/// <summary>
		/// Metadata information for the 'Size' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'Size' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Size", AutoGenerateField = true)]
		public object Size;

		/// <summary>
		/// Metadata information for the 'StorageSize' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'StorageSize' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "StorageSize", AutoGenerateField = true)]
		public object StorageSize;

		/// <summary>
		/// Metadata information for the 'TenantID' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'TenantID' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "TenantID", AutoGenerateField = true)]
		public object TenantID;

		/// <summary>
		/// Metadata information for the 'UniqueKey' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'UniqueKey' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "UniqueKey", AutoGenerateField = true)]
		public object UniqueKey;

		/// <summary>
		/// Metadata information for the 'CreatedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'CreatedBy' has a maximum length of 100")]
		[System.ComponentModel.ReadOnly(true)]
		public object CreatedBy;

		/// <summary>
		/// Metadata information for the 'CreatedDate' parameter
		/// </summary>
		[System.ComponentModel.ReadOnly(true)]
		public object CreatedDate;

		/// <summary>
		/// Metadata information for the 'ModifiedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'ModifiedBy' has a maximum length of 100")]
		[System.ComponentModel.ReadOnly(true)]
		public object ModifiedBy;

		/// <summary>
		/// Metadata information for the 'ModifiedDate' parameter
		/// </summary>
		[System.ComponentModel.ReadOnly(true)]
		public object ModifiedDate;

		/// <summary>
		/// Metadata information for the 'Timestamp' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Timestamp()]
		[System.ComponentModel.DataAnnotations.ConcurrencyCheck()]
		[System.ComponentModel.ReadOnly(true)]
		public object Timestamp;

		#endregion

		#region Methods
		/// <summary>
		/// Gets the underlying table name.
		/// </summary>
		public virtual string GetTableName()
		{
			return "FileStash";
		}

		/// <summary>
		/// Gets a list of all object fields with alias/code facade applied excluding inheritance.
		/// </summary>
		public virtual List<string> GetFields()
		{
			var retval = new List<string>();
			retval.Add("ContainerId");
			retval.Add("CrcPlain");
			retval.Add("FileStashID");
			retval.Add("IsCompressed");
			retval.Add("Path");
			retval.Add("Size");
			retval.Add("StorageSize");
			retval.Add("TenantID");
			retval.Add("UniqueKey");
			return retval;
		}

		/// <summary>
		/// Returns the type of the parent object if one exists.
		/// </summary>
		public virtual System.Type InheritsFrom()
		{
			return null;
		}

		/// <summary>
		/// Returns the database schema name.
		/// </summary>
		public virtual string Schema()
		{
			return "dbo";
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		public virtual string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "ContainerId": return "ContainerId";
				case "CrcPlain": return "CrcPlain";
				case "FileStashID": return "FileStashID";
				case "IsCompressed": return "IsCompressed";
				case "Path": return "Path";
				case "Size": return "Size";
				case "StorageSize": return "StorageSize";
				case "TenantID": return "TenantID";
				case "UniqueKey": return "UniqueKey";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

	}

}

#endregion

#pragma warning restore 612

