//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 612
using System;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.Generic;
using System.Text;
using Gravitybox.gFileSystem.EFDAL;
using Gravitybox.gFileSystem.EFDAL.EventArguments;
using System.Text.RegularExpressions;
using System.Linq.Expressions;
using System.Data.Entity;
using System.Data.Linq;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations;

namespace Gravitybox.gFileSystem.EFDAL.Entity
{
	/// <summary>
	/// The 'Tenant' entity
	/// </summary>
	[DataContract]
	[Serializable]
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	[FieldNameConstants(typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants))]
	[System.ComponentModel.DataAnnotations.MetadataType(typeof(Gravitybox.gFileSystem.EFDAL.Entity.Metadata.TenantMetadata))]
	[EntityMetadata("Tenant", false, true, true, true, "", true, false, false, "dbo")]
	public partial class Tenant : BaseEntity, Gravitybox.gFileSystem.EFDAL.IBusinessObject, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging, System.ICloneable, Gravitybox.gFileSystem.EFDAL.IAuditable, Gravitybox.gFileSystem.EFDAL.IAuditableSet, Gravitybox.gFileSystem.EFDAL.ICreatable
	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'Tenant' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'Key' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Key' property")]
			Key,
			/// <summary>
			/// Field mapping for the 'Name' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Name' property")]
			Name,
			/// <summary>
			/// Field mapping for the 'TenantID' property
			/// </summary>
			[System.ComponentModel.DataAnnotations.Key]
			[System.ComponentModel.ReadOnly(true)]
			[System.ComponentModel.Description("Field mapping for the 'TenantID' property")]
			TenantID,
			/// <summary>
			/// Field mapping for the 'UniqueKey' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'UniqueKey' property")]
			UniqueKey,
			/// <summary>
			/// Field mapping for the 'CreatedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedBy' property")]
			CreatedBy,
			/// <summary>
			/// Field mapping for the 'CreatedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'CreatedDate' property")]
			CreatedDate,
			/// <summary>
			/// Field mapping for the 'ModifiedBy' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedBy' property")]
			ModifiedBy,
			/// <summary>
			/// Field mapping for the 'ModifiedDate' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'ModifiedDate' property")]
			ModifiedDate,
		}
		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the Gravitybox.gFileSystem.EFDAL.Entity.Tenant class
		/// </summary>
		public Tenant()
		{
			this._uniqueKey = Guid.NewGuid();

		}

		#endregion

		#region Properties

		/// <summary>
		/// The property that maps back to the database 'Tenant.Key' field.
		/// </summary>
		/// <remarks>Field: [Tenant].[Key], Field Length: 48, Not Nullable</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Key")]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual System.Byte[] Key
		{
			get { return _key; }
			set
			{
				if (value == _key) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Byte[]>(value, "Key");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_key = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Key"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Tenant.Name' field.
		/// </summary>
		/// <remarks>Field: [Tenant].[Name], Field Length: 50, Not Nullable, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("Name")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string Name
		{
			get { return _name; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Name))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Tenant.Name", GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Name)));
				if (value == _name) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "Name");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_name = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Name"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Tenant.TenantID' field.
		/// </summary>
		/// <remarks>Field: [Tenant].[TenantID], Not Nullable, Primary Key, AutoNumber, Unique, Indexed</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("TenantID")]
		[System.ComponentModel.DataAnnotations.Schema.Index(IsUnique = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual long TenantID
		{
			get { return _tenantID; }
			protected internal set
			{
				if (value == _tenantID) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>(value, "TenantID");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_tenantID = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("TenantID"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Tenant.UniqueKey' field.
		/// </summary>
		/// <remarks>Field: [Tenant].[UniqueKey], Not Nullable, Indexed, Default Value: newid</remarks>
		[DataMember]
		[System.ComponentModel.Browsable(true)]
		[System.ComponentModel.DisplayName("UniqueKey")]
		[System.ComponentModel.DataAnnotations.Schema.Index()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual System.Guid UniqueKey
		{
			get { return _uniqueKey; }
			set
			{
				if (value == _uniqueKey) return;
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Guid>(value, "UniqueKey");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_uniqueKey = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("UniqueKey"));
			}
		}

		/// <summary>
		/// The audit field for the 'Created By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string CreatedBy
		{
			get { return _createdby; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "CreatedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createdby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedBy"));
			}
		}

		/// <summary />
		protected string _createdby;

		/// <summary>
		/// The audit field for the 'Created Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual DateTime? CreatedDate
		{
			get { return _createddate; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>(value, "CreatedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_createddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("CreatedDate"));
			}
		}

		/// <summary />
		protected DateTime? _createddate;

		/// <summary>
		/// The audit field for the 'Modified By' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual string ModifiedBy
		{
			get { return _modifiedby; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>(value, "ModifiedBy");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifiedby = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedBy"));
			}
		}

		/// <summary />
		protected string _modifiedby;

		/// <summary>
		/// The audit field for the 'Modified Date' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual DateTime? ModifiedDate
		{
			get { return _modifieddate; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>(value, "ModifiedDate");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_modifieddate = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("ModifiedDate"));
			}
		}

		/// <summary />
		protected DateTime? _modifieddate;

		/// <summary>
		/// The audit field for the 'Timestamp' parameter.
		/// </summary>
		[System.ComponentModel.Browsable(false)]
		[DataMember()]
		[System.Diagnostics.DebuggerNonUserCode()]
		public virtual byte[] Timestamp
		{
			get { return _timestamp; }
			protected internal set
			{
				var eventArg = new Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<byte[]>(value, "Timestamp");
				this.OnPropertyChanging(eventArg);
				if (eventArg.Cancel) return;
				_timestamp = eventArg.Value;
				this.OnPropertyChanged(new PropertyChangedEventArgs("Timestamp"));
			}
		}

		/// <summary />
		protected byte[] _timestamp;

		#endregion

		#region Property Holders

		/// <summary />
		protected System.Byte[] _key;
		/// <summary>
		/// Occurs when the 'Key' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Byte[]>> KeyChanging;

		/// <summary>
		/// Raises the OnKeyChanging event.
		/// </summary>
		protected virtual void OnKeyChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Byte[]> e)
		{
			if (this.KeyChanging != null)
				this.KeyChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Key' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<System.Byte[]>> KeyChanged;

		/// <summary>
		/// Raises the OnKeyChanged event.
		/// </summary>
		protected virtual void OnKeyChanged(ChangedEventArgs<System.Byte[]> e)
		{
			if (this.KeyChanged != null)
				this.KeyChanged(this, e);
		}

		/// <summary />
		protected string _name;
		/// <summary>
		/// Occurs when the 'Name' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> NameChanging;

		/// <summary>
		/// Raises the OnNameChanging event.
		/// </summary>
		protected virtual void OnNameChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.NameChanging != null)
				this.NameChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Name' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> NameChanged;

		/// <summary>
		/// Raises the OnNameChanged event.
		/// </summary>
		protected virtual void OnNameChanged(ChangedEventArgs<string> e)
		{
			if (this.NameChanged != null)
				this.NameChanged(this, e);
		}

		/// <summary />
		protected long _tenantID;
		/// <summary>
		/// Occurs when the 'TenantID' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long>> TenantIDChanging;

		/// <summary>
		/// Raises the OnTenantIDChanging event.
		/// </summary>
		protected virtual void OnTenantIDChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<long> e)
		{
			if (this.TenantIDChanging != null)
				this.TenantIDChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'TenantID' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<long>> TenantIDChanged;

		/// <summary>
		/// Raises the OnTenantIDChanged event.
		/// </summary>
		protected virtual void OnTenantIDChanged(ChangedEventArgs<long> e)
		{
			if (this.TenantIDChanged != null)
				this.TenantIDChanged(this, e);
		}

		/// <summary />
		protected System.Guid _uniqueKey;
		/// <summary>
		/// Occurs when the 'UniqueKey' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Guid>> UniqueKeyChanging;

		/// <summary>
		/// Raises the OnUniqueKeyChanging event.
		/// </summary>
		protected virtual void OnUniqueKeyChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<System.Guid> e)
		{
			if (this.UniqueKeyChanging != null)
				this.UniqueKeyChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'UniqueKey' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<System.Guid>> UniqueKeyChanged;

		/// <summary>
		/// Raises the OnUniqueKeyChanged event.
		/// </summary>
		protected virtual void OnUniqueKeyChanged(ChangedEventArgs<System.Guid> e)
		{
			if (this.UniqueKeyChanged != null)
				this.UniqueKeyChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> CreatedByChanging;

		/// <summary>
		/// Raises the OnCreatedByChanging event.
		/// </summary>
		protected virtual void OnCreatedByChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.CreatedByChanging != null)
				this.CreatedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedBy' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> CreatedByChanged;

		/// <summary>
		/// Raises the OnCreatedByChanged event.
		/// </summary>
		protected virtual void OnCreatedByChanged(ChangedEventArgs<string> e)
		{
			if (this.CreatedByChanged != null)
				this.CreatedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>> CreatedDateChanging;

		/// <summary>
		/// Raises the OnCreatedDateChanging event.
		/// </summary>
		protected virtual void OnCreatedDateChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?> e)
		{
			if (this.CreatedDateChanging != null)
				this.CreatedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'CreatedDate' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<DateTime?>> CreatedDateChanged;

		/// <summary>
		/// Raises the OnCreatedDateChanged event.
		/// </summary>
		protected virtual void OnCreatedDateChanged(ChangedEventArgs<DateTime?> e)
		{
			if (this.CreatedDateChanged != null)
				this.CreatedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string>> ModifiedByChanging;

		/// <summary>
		/// Raises the OnModifiedByChanging event.
		/// </summary>
		protected virtual void OnModifiedByChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<string> e)
		{
			if (this.ModifiedByChanging != null)
				this.ModifiedByChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedBy' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<string>> ModifiedByChanged;

		/// <summary>
		/// Raises the OnModifiedByChanged event.
		/// </summary>
		protected virtual void OnModifiedByChanged(ChangedEventArgs<string> e)
		{
			if (this.ModifiedByChanged != null)
				this.ModifiedByChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?>> ModifiedDateChanging;

		/// <summary>
		/// Raises the OnModifiedDateChanging event.
		/// </summary>
		protected virtual void OnModifiedDateChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<DateTime?> e)
		{
			if (this.ModifiedDateChanging != null)
				this.ModifiedDateChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'ModifiedDate' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<DateTime?>> ModifiedDateChanged;

		/// <summary>
		/// Raises the OnModifiedDateChanged event.
		/// </summary>
		protected virtual void OnModifiedDateChanged(ChangedEventArgs<DateTime?> e)
		{
			if (this.ModifiedDateChanged != null)
				this.ModifiedDateChanged(this, e);
		}

		/// <summary>
		/// Occurs when the 'Timestamp' property value change is a pending.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<byte[]>> TimestampChanging;

		/// <summary>
		/// Raises the OnTimestampChanging event.
		/// </summary>
		protected virtual void OnTimestampChanging(Gravitybox.gFileSystem.EFDAL.EventArguments.ChangingEventArgs<byte[]> e)
		{
			if (this.TimestampChanging != null)
				this.TimestampChanging(this, e);
		}

		/// <summary>
		/// Occurs when the 'Timestamp' property value has changed.
		/// </summary>
		[field:NonSerialized]
		public event EventHandler<ChangedEventArgs<byte[]>> TimestampChanged;

		/// <summary>
		/// Raises the OnTimestampChanged event.
		/// </summary>
		protected virtual void OnTimestampChanged(ChangedEventArgs<byte[]> e)
		{
			if (this.TimestampChanged != null)
				this.TimestampChanged(this, e);
		}


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field)
		{
			switch (field)
			{
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Key:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Name:
					return 50;
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.TenantID:
					return 0;
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.UniqueKey:
					return 0;
			}
			return 0;
		}

		int Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetMaxLength(Enum field)
		{
			return GetMaxLength((Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants)field);
		}

		#endregion

		#region GetFieldNameConstants

		System.Type Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetFieldNameConstants()
		{
			return typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants);
		}

		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants'.");

			switch ((Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants)field)
			{
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Key: return typeof(System.Byte[]);
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Name: return typeof(string);
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.TenantID: return typeof(long);
				case Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.UniqueKey: return typeof(System.Guid);
			}
			return null;
		}

		System.Type Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetFieldType(Enum field)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants'.");

			return GetFieldType((Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants)field);
		}

		#endregion

		#region Get/Set Value

		object Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field)
		{
			return ((Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject)this).GetValue(field, null);
		}

		object Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.GetValue(System.Enum field, object defaultValue)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants'.");
			return this.GetValue((Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants)field, defaultValue);
		}

		void Gravitybox.gFileSystem.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants'.");
			this.SetValue((Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants)field, newValue);
		}

		void Gravitybox.gFileSystem.EFDAL.IBusinessObject.SetValue(System.Enum field, object newValue, bool fixLength)
		{
			if (field.GetType() != typeof(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants))
				throw new Exception("The field parameter must be of type 'Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants'.");
			this.SetValue((Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants)field, newValue, fixLength);
		}

		#endregion

		#region PrimaryKey

		/// <summary>
		/// Generic primary key for this object
		/// </summary>
		Gravitybox.gFileSystem.EFDAL.IPrimaryKey Gravitybox.gFileSystem.EFDAL.IReadOnlyBusinessObject.PrimaryKey
		{
			get { return new PrimaryKey(Util.HashPK("Tenant", this.TenantID)); }
		}

		#endregion

		#region Clone

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public virtual object Clone()
		{
			return Gravitybox.gFileSystem.EFDAL.Entity.Tenant.Clone(this);
		}

		/// <summary>
		/// Creates a shallow copy of this object with defined, default values and new PK
		/// </summary>
		public virtual object CloneAsNew()
		{
			var item = Gravitybox.gFileSystem.EFDAL.Entity.Tenant.Clone(this);
			item._tenantID = 0;
			item._uniqueKey = Guid.NewGuid();
			return item;
		}

		/// <summary>
		/// Creates a shallow copy of this object
		/// </summary>
		public static Tenant Clone(Gravitybox.gFileSystem.EFDAL.Entity.Tenant item)
		{
			var newItem = new Tenant();
			newItem.Key = item.Key;
			newItem.Name = item.Name;
			newItem.TenantID = item.TenantID;
			newItem.UniqueKey = item.UniqueKey;
			newItem.CreatedDate = item.CreatedDate;
			newItem.CreatedBy = item.CreatedBy;
			newItem.ModifiedDate = item.ModifiedDate;
			newItem.ModifiedBy = item.ModifiedBy;
			return newItem;
		}

		#endregion

		#region GetValue

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field)
		{
			return GetValue(field, null);
		}

		/// <summary>
		/// Gets the value of one of this object's properties.
		/// </summary>
		public virtual object GetValue(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field, object defaultValue)
		{
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Key)
				return this.Key;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Name)
				return this.Name;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.TenantID)
				return this.TenantID;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.UniqueKey)
				return this.UniqueKey;
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.CreatedBy)
				return ((this.CreatedBy == null) ? defaultValue : this.CreatedBy);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.CreatedDate)
				return ((this.CreatedDate == null) ? defaultValue : this.CreatedDate);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.ModifiedBy)
				return ((this.ModifiedBy == null) ? defaultValue : this.ModifiedBy);
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.ModifiedDate)
				return ((this.ModifiedDate == null) ? defaultValue : this.ModifiedDate);
			throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region SetValue

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		public virtual void SetValue(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field, object newValue)
		{
			SetValue(field, newValue, false);
		}

		/// <summary>
		/// Assigns a value to a field on this object.
		/// </summary>
		/// <param name="field">The field to set</param>
		/// <param name="newValue">The new value to assign to the field</param>
		/// <param name="fixLength">Determines if the length should be truncated if too long. When false, an error will be raised if data is too large to be assigned to the field.</param>
		public virtual void SetValue(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field, object newValue, bool fixLength)
		{
			if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Key)
			{
				if (newValue == null)
				{
					throw new Exception("Field 'Key' does not allow null values!");
				}
				else
				{
					this.Key = (System.Byte[])newValue;
				}
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.Name)
			{
				this.Name = GlobalValues.SetValueHelperInternal((string)newValue, fixLength, GetMaxLength(field));
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.TenantID)
			{
				throw new Exception("Field '" + field.ToString() + "' is a primary key and cannot be set!");
			}
			else if (field == Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants.UniqueKey)
			{
				if (newValue == null)
				{
					throw new Exception("Field 'UniqueKey' does not allow null values!");
				}
				else
				{
					this.UniqueKey = (System.Guid)newValue;
				}
			}
			else
				throw new Exception("Field '" + field.ToString() + "' not found!");
		}

		#endregion

		#region Navigation Properties

		/// <summary>
		/// The navigation definition for walking Tenant->FileStash
		/// </summary>
		[DataMember]
		[XmlIgnore]
		public virtual ICollection<Gravitybox.gFileSystem.EFDAL.Entity.FileStash> FileStashList
		{
			get
			{
				if (_FileStashList == null) _FileStashList = new List<Gravitybox.gFileSystem.EFDAL.Entity.FileStash>();
				return _FileStashList;
			}
			set { _FileStashList = value; }
		}
		/// <summary />
		protected virtual ICollection<Gravitybox.gFileSystem.EFDAL.Entity.FileStash> _FileStashList { get; set; }

		#endregion

		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "key": return "key";
				case "name": return "name";
				case "tenantid": return "tenantid";
				case "uniquekey": return "uniquekey";
				case "createddate": return "createddate";
				case "createdby": return "createdby";
				case "modifieddate": return "modifieddate";
				case "modifiedby": return "modifiedby";
				case "timestamp": return "timestamp";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "key": return "Tenant";
				case "name": return "Tenant";
				case "tenantid": return "Tenant";
				case "uniquekey": return "Tenant";
				case "createdby": return "Tenant";
				case "createddate": return "Tenant";
				case "modifiedby": return "Tenant";
				case "modifieddate": return "Tenant";
				case "timestamp": return "Tenant";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "key": return "Tenant";
				case "name": return "Tenant";
				case "tenantid": return "Tenant";
				case "uniquekey": return "Tenant";
				case "createdby": return "Tenant";
				case "createddate": return "Tenant";
				case "modifiedby": return "Tenant";
				case "modifieddate": return "Tenant";
				case "timestamp": return "Tenant";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[key\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[key]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[name\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[name]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[tenantid\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[tenantid]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[uniquekey\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[uniquekey]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createdby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[createdby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[createddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[createddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifiedby\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[modifiedby]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[modifieddate\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[modifieddate]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[timestamp\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Tenant") + "].[timestamp]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion

		#region DeleteData

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: Gravitybox.gFileSystem.EFDAL.gFileSystemEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, QueryOptimizer optimizer)
		{
			return DeleteData(where: where, optimizer: optimizer, startup: new ContextStartup(null), connectionString: Gravitybox.gFileSystem.EFDAL.gFileSystemEntities.GetConnectionString());
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, string connectionString)
		{
			return DeleteData(where: where, optimizer: new QueryOptimizer(), startup: new ContextStartup(null), connectionString: connectionString);
		}

		/// <summary>
		/// Delete all records that match a where condition
		/// </summary>
		/// <param name="where">The expression that determines the records deleted</param>
		/// <param name="optimizer">The optimization object to use for running queries</param>
		/// <param name="startup">The startup options</param>
		/// <param name="connectionString">The database connection string to use for this access</param>
		/// <returns>The number of rows deleted</returns>
		public static int DeleteData(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, QueryOptimizer optimizer, ContextStartup startup, string connectionString)
		{
			if (optimizer == null)
				optimizer = new QueryOptimizer();
				if (startup == null) startup = new ContextStartup(null);

			using (var connection = Gravitybox.gFileSystem.EFDAL.DBHelper.GetConnection(Gravitybox.gFileSystem.EFDAL.Util.StripEFCS2Normal(connectionString)))
			{
				using (var dc = new DataContext(connection))
				{
					var template = dc.GetTable<Gravitybox.gFileSystem.EFDAL.TenantQuery>();
					using (var cmd = BusinessEntityQuery.GetCommand<Gravitybox.gFileSystem.EFDAL.TenantQuery>(dc, template, where))
					{
						if (!startup.DefaultTimeout && startup.CommandTimeout > 0) cmd.CommandTimeout = startup.CommandTimeout;
						else
						{
							var cb = new System.Data.SqlClient.SqlConnectionStringBuilder(connectionString);
							cmd.CommandTimeout = cb.ConnectTimeout;
						}

						var parser = LinqSQLParser.Create(cmd.CommandText, LinqSQLParser.ObjectTypeConstants.Table);
						var sql = "CREATE TABLE #t ([TenantID] [BigInt])";
						sql += "set rowcount " + optimizer.ChunkSize + ";";
						sql += "INSERT INTO #t ([TenantID])";
						sql += "SELECT [t0].[TenantID] #t\r\n";
						sql += parser.GetFromClause(optimizer) + "\r\n";
						sql += parser.GetWhereClause();
						sql += "\r\n";

						var noLock = string.Empty;
						noLock = (optimizer.NoLocking ? "WITH (READUNCOMMITTED) " : string.Empty);
						sql += "DELETE [Tenant] FROM [dbo].[Tenant] " + noLock + "INNER JOIN #t ON [dbo].[Tenant].[TenantID] = #t.[TenantID]\r\n";
						sql += ";select @@rowcount";
						sql = "set ansi_nulls off;" + sql + ";drop table #t;";
						cmd.CommandText = sql;
						dc.Connection.Open();
						var startTime = DateTime.Now;
						var affected = 0;
						var count = 0;
						do
						{
							count = (int)cmd.ExecuteScalar();
							affected += count;
						} while (count > 0 && optimizer.ChunkSize > 0);
						var endTime = DateTime.Now;
						optimizer.TotalMilliseconds = (long)endTime.Subtract(startTime).TotalMilliseconds;
						dc.Connection.Close();
						return affected;
					}
				}
			}
		}

		#endregion

		#region UpdateData

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, TSource newValue)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.Tenant, Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Tenant", getField: GetDatabaseFieldName, hasModifyAudit: true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connection">An open database connection</param>
		/// <param name="transaction">The database connection transaction</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, TSource newValue, System.Data.IDbConnection connection, System.Data.Common.DbTransaction transaction)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.Tenant, Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Tenant", getField: GetDatabaseFieldName, hasModifyAudit: true, startup: null, connection: connection, transaction: transaction);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="startup">A configuration object</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, TSource newValue, ContextStartup startup, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.Tenant, Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Tenant", getField: GetDatabaseFieldName, hasModifyAudit: true, startup: startup, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, TSource newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.Tenant, Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Tenant", getField: GetDatabaseFieldName, hasModifyAudit: true, connectionString: connectionString);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, Gravitybox.gFileSystem.EFDAL.Entity.Tenant newValue)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.Tenant, Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Tenant", getField: GetDatabaseFieldName, hasModifyAudit: true);
		}

		/// <summary>
		/// Update the specified field that matches the Where expression with the new data value
		/// </summary>
		/// <param name="select">The field to update</param>
		/// <param name="where">The expression that determines the records selected</param>
		/// <param name="newValue">The new value to set the specified field in all matching records</param>
		/// <param name="connectionString">The database connection string</param>
		/// <returns>The number of records affected</returns>
		public static int UpdateData<TSource>(Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>> select, Expression<Func<Gravitybox.gFileSystem.EFDAL.TenantQuery, bool>> where, Gravitybox.gFileSystem.EFDAL.Entity.Tenant newValue, string connectionString)
		{
			return BusinessObjectQuery<Gravitybox.gFileSystem.EFDAL.Entity.Tenant, Gravitybox.gFileSystem.EFDAL.TenantQuery, TSource>.UpdateData(select: select, where: where, newValue: newValue, leafTable: "Tenant", getField: GetDatabaseFieldName, hasModifyAudit: true, connectionString: connectionString);
		}

		#endregion

		#region GetDatabaseFieldName

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(Gravitybox.gFileSystem.EFDAL.Entity.Tenant.FieldNameConstants field)
		{
			return GetDatabaseFieldName(field.ToString());
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		internal static string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "Key": return "Key";
				case "Name": return "Name";
				case "TenantID": return "TenantID";
				case "UniqueKey": return "UniqueKey";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

		#region Auditing
		string Gravitybox.gFileSystem.EFDAL.IAuditableSet.CreatedBy
		{
			get { return this.CreatedBy; }
			set { this.CreatedBy = value; }
		}

		string Gravitybox.gFileSystem.EFDAL.IAuditableSet.ModifiedBy
		{
			get { return this.ModifiedBy; }
			set { this.ModifiedBy = value; }
		}
		string Gravitybox.gFileSystem.EFDAL.IAuditable.CreatedBy
		{
			get { return this.CreatedBy; }
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditable.CreatedDate
		{
			get { return this.CreatedDate; }
		}

		bool Gravitybox.gFileSystem.EFDAL.IAuditable.IsCreateAuditImplemented
		{
			get { return true; }
		}

		bool Gravitybox.gFileSystem.EFDAL.IAuditable.IsModifyAuditImplemented
		{
			get { return true; }
		}

		bool Gravitybox.gFileSystem.EFDAL.IAuditable.IsTimestampAuditImplemented
		{
			get { return true; }
		}

		string Gravitybox.gFileSystem.EFDAL.IAuditable.ModifiedBy
		{
			get { return this.ModifiedBy; }
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditable.ModifiedDate
		{
			get { return this.ModifiedDate; }
		}

		byte[] Gravitybox.gFileSystem.EFDAL.IAuditable.TimeStamp
		{
			get { return this.Timestamp; }
		}

		void IAuditableSet.ResetModifiedBy(string modifier)
		{
			if (this.ModifiedBy != modifier)
				this.ModifiedBy = modifier;
		}

		void IAuditableSet.ResetCreatedBy(string modifier)
		{
			if (this.CreatedBy != modifier)
				this.CreatedBy = modifier;
			((IAuditableSet)this).ResetModifiedBy(modifier);
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditableSet.CreatedDate
		{
			get { return this.CreatedDate; }
			set { this.CreatedDate = value; }
		}

		System.DateTime? Gravitybox.gFileSystem.EFDAL.IAuditableSet.ModifiedDate
		{
			get { return this.ModifiedDate; }
			set { this.ModifiedDate = value; }
		}

		#endregion

		#region Equals
		/// <summary>
		/// Compares two objects of 'Tenant' type and determines if all properties match
		/// </summary>
		/// <returns>True if all properties match, false otherwise</returns>
		public override bool Equals(object obj)
		{
			var other = obj as Gravitybox.gFileSystem.EFDAL.Entity.Tenant;
			if (other == null) return false;
			return (
				other.Key == this.Key &&
				other.Name == this.Name &&
				other.TenantID == this.TenantID &&
				other.UniqueKey == this.UniqueKey
				);
		}

		/// <summary>
		/// Serves as a hash function for this type.
		/// </summary>
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}

		#endregion

	}
}

#region Metadata Class

namespace Gravitybox.gFileSystem.EFDAL.Entity.Metadata
{
	/// <summary>
	/// Metadata class for the 'Tenant' entity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "6.0.0")]
	public partial class TenantMetadata : Gravitybox.gFileSystem.EFDAL.IMetadata
	{
		#region Properties

		/// <summary>
		/// Metadata information for the 'Key' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'Key' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Key", AutoGenerateField = true)]
		public object Key;

		/// <summary>
		/// Metadata information for the 'Name' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'Name' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.StringLength(50, ErrorMessage = "The property 'Name' has a maximum length of 50")]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "Name", AutoGenerateField = true)]
		public object Name;

		/// <summary>
		/// Metadata information for the 'TenantID' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'TenantID' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Key()]
		[System.ComponentModel.ReadOnly(true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "TenantID", AutoGenerateField = true)]
		public object TenantID;

		/// <summary>
		/// Metadata information for the 'UniqueKey' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Required(ErrorMessage = "'UniqueKey' is required.", AllowEmptyStrings = true)]
		[System.ComponentModel.DataAnnotations.Display(Description = "", Name = "UniqueKey", AutoGenerateField = true)]
		public object UniqueKey;

		/// <summary>
		/// Metadata information for the 'CreatedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'CreatedBy' has a maximum length of 100")]
		[System.ComponentModel.ReadOnly(true)]
		public object CreatedBy;

		/// <summary>
		/// Metadata information for the 'CreatedDate' parameter
		/// </summary>
		[System.ComponentModel.ReadOnly(true)]
		public object CreatedDate;

		/// <summary>
		/// Metadata information for the 'ModifiedBy' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.StringLength(100, ErrorMessage = "The property 'ModifiedBy' has a maximum length of 100")]
		[System.ComponentModel.ReadOnly(true)]
		public object ModifiedBy;

		/// <summary>
		/// Metadata information for the 'ModifiedDate' parameter
		/// </summary>
		[System.ComponentModel.ReadOnly(true)]
		public object ModifiedDate;

		/// <summary>
		/// Metadata information for the 'Timestamp' parameter
		/// </summary>
		[System.ComponentModel.DataAnnotations.Timestamp()]
		[System.ComponentModel.DataAnnotations.ConcurrencyCheck()]
		[System.ComponentModel.ReadOnly(true)]
		public object Timestamp;

		#endregion

		#region Methods
		/// <summary>
		/// Gets the underlying table name.
		/// </summary>
		public virtual string GetTableName()
		{
			return "Tenant";
		}

		/// <summary>
		/// Gets a list of all object fields with alias/code facade applied excluding inheritance.
		/// </summary>
		public virtual List<string> GetFields()
		{
			var retval = new List<string>();
			retval.Add("Key");
			retval.Add("Name");
			retval.Add("TenantID");
			retval.Add("UniqueKey");
			return retval;
		}

		/// <summary>
		/// Returns the type of the parent object if one exists.
		/// </summary>
		public virtual System.Type InheritsFrom()
		{
			return null;
		}

		/// <summary>
		/// Returns the database schema name.
		/// </summary>
		public virtual string Schema()
		{
			return "dbo";
		}

		/// <summary>
		/// Returns the actual database name of the specified field.
		/// </summary>
		public virtual string GetDatabaseFieldName(string field)
		{
			switch (field)
			{
				case "Key": return "Key";
				case "Name": return "Name";
				case "TenantID": return "TenantID";
				case "UniqueKey": return "UniqueKey";
				case "CreatedBy": return "CreatedBy";
				case "CreatedDate": return "CreatedDate";
				case "ModifiedBy": return "ModifiedBy";
				case "ModifiedDate": return "ModifiedDate";
				case "Timestamp": return "Timestamp";
			}
			return string.Empty;
		}

		#endregion

	}

}

#endregion

#pragma warning restore 612

