--DO NOT MODIFY THIS FILE. IT IS ALWAYS OVERWRITTEN ON GENERATION.
--Static Data

if (SERVERPROPERTY('EngineEdition') <> 5) --NOT AZURE
exec sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'

if (SERVERPROPERTY('EngineEdition') <> 5) --NOT AZURE
exec sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'

